# -*- coding: utf-8 -*-
"""2110993799_Ishita.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrdpaC0fQaVnMZJU4EgFwEQhIa6KARC4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#loading dataset
data=pd.read_excel("Sample Survey.xlsx",'Data')

survey=pd.DataFrame(data)
survey

#calculating samples_day
samples_day=survey.groupby("collection_date").size()
print(samples_day)

survey['age'] = pd.to_numeric(survey['age'], errors='coerce')

ques_three=survey[survey['age'] < 45]
p=len(ques_three)/len(survey)
print(p)

a=[18, 25, 40, 55, float('inf')]
labels=['18-25', '25-40', '40-55', '55+']

survey['age_group'] = pd.cut(survey['age'], bins=a, labels=labels, right=False)
print(survey[['age', 'age_group']].head())

rjd=survey[(survey['Vote_Now'] == 'RJD') & (survey['Past_Vote'] == 'RJD')]
pr=len(rjd)/len(survey)
print(pr)

samples_age=survey.groupby("age_group").size()
print(samples_age)

max_samples=samples_age.idxmax()
print(max_samples)

cm=survey.groupby('collection_date')['CM_satisfaction'].apply(lambda x: (x == 'Fully Satisfied').mean())
print(cm)

mla=survey.groupby('collection_date')['MLA_satisfaction'].apply(lambda x: (x == 'Fully Dissatisfied').mean())
print(mla)

plt.figure(figsize=(10, 6))
mla.plot(kind='line')
plt.xlabel('Date')
plt.ylabel('Proportion')
plt.show()

pivot_table=pd.pivot_table(survey, index='Past_Vote', columns='Vote_Now', aggfunc='size', fill_value=0)
print(pivot_table)

pivot_table2=pd.pivot_table(survey, index='Past_Vote', columns='Vote_Now', values='weight', aggfunc='sum', fill_value=0)
print(pivot_table2)

age_s=survey.groupby('age_group').size().reset_index(name='total_samples')
print(age_s)

age_df=pd.DataFrame(age_s)
age_df

jdu=survey[survey['Vote_Now'] == 'JD(U)']
jdu_samples= jdu.groupby('age_group').size().reset_index(name='jd_u_samples_count')
print(jdu_samples)

jdu_df=pd.DataFrame(jdu_samples)
jdu_df

